services:
  googlarr:
    container_name: googlarr
    build:
      context: <cloned repository location>
      dockerfile: Dockerfile
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /path/to/config:/app/config
      - /path/to/data:/app/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
